#!/bin/sh

until confd -onetime -node https://89.106.37.119:4001 -config-file /etc/confd/confd.toml; do
  echo "[confd] waiting for confd to refresh config files"
  sleep 5
done

exec /usr/bin/supervisord
