#!/bin/sh

until confd -onetime -node http://$(ip route show dev eth0 | grep default | awk '{print $3}'):4001 -config-file /etc/confd/confd.toml; do
  echo "[confd] waiting for confd to refresh config files"
  sleep 5
done

exec /usr/bin/supervisord
